spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    resources:
    static-locations:
    - classpath:/resources/
mybatis:
  mapper-locations:  - classpath:mapper/*.xml
 
